### ISSUE TITLE
Version aligment

### ISSUE THREAD

**Issue by arkadiuszczapiewskinordea** [NordeaOSS/devtool#2] opened 2018-01-31 12:27 UTC
In Nordea we have v1.37 of DevTool and here on GitHub it is v1.35. Can we align to v1.37?

**Comment by holmbech** [comment] 2018-02-01 18:40
Hi,

Sure. Could you maybe check if there have been any changes in the Nordea version that maybe needs to be updated here?

**Comment by RocketRunner** [comment] 2018-02-02 08:24
I will follow up on that!

**Comment by holmbech** [comment] 2018-02-06 12:52
Anything new on this one @RocketRunner?

**Comment by holmbech** [comment] 2018-02-17 15:45
Whats up @RocketRunner?

**Comment by RocketRunner** [comment] 2018-02-26 12:56
the Rocket has landed and is now again within radio reach... :-)

I have compared the differences between the versions

Since the fork the internal version has been updated with:
curl-ca-bundle.crt

Since the fork the external version has been:
parameterized in regards to nexus and confluence urls

The CA bundle has already been added to the external version, so all in all they should be the same.

**Comment by RocketRunner** [comment] 2018-02-26 12:58
The problem is that in some cases the users has another version of CURL in the classpath and when they do it seems to be ignoring the CA bundle. 

Therefor we still have -insecure added to the curl command to ignore internal signed certificates

**Comment by RocketRunner** [comment] 2018-02-27 08:06
I have Bumped the version to 1.37

**Closed as completed by RocketRunner** 2018-02-27 08:06 UTC
